import { About } from '@/components/about'
import { Header } from '@/components/header'
import { Sidebar } from '@/components/sidebar'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>About Me - Gilberto Medeiros</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');
        </style>
      </Head>
      <main>
        <Header></Header>
        <div className='container'>
          <div className='row'>
            <Sidebar/>
            <About/>
          </div>
        </div>
      </main>
    </>
  )
}
