import { Header } from "@/components/header";
import { Publications } from "@/components/publications";
import { Sidebar } from "@/components/sidebar";
import Head from "next/head";

export default function PublicationsPage () {
    return <>
        <Head>
            <title>About Me - Gilberto Medeiros</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            <style>
            @import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');
            </style>
        </Head>
        <main>
            <Header></Header>
            <div className='container'>
            <div className='row'>
                <Sidebar/>
                <Publications/>
            </div>
            </div>
        </main>
    </>
}